version: '3.8'
networks:
    backend-network:
        internal: true
        driver: bridge
    traefik-network:
        external: true
        driver: bridge
services:
    frontend:
        image: prytaneum/frontend:latest
        networks:
            - traefik-network
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.frontend.rule=PathPrefix(`/`)'
    backend:
        environment: 
          - DB_URL=mongodb://mongo
        image: prytaneum/backend:latest
        networks:
            - backend-network
            - traefik-network
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.backend.rule=PathPrefix(`/api`) || PathPrefix(`/chat`) || PathPrefix(`/socket.io`)'
        # ports:
        #     - 3001:3000
    backend-db:
        image: mongo:4.2.8-bionic
        networks:
            backend-network:
                aliases:
                    - mongo
    traefik:
        image: 'traefik:v2.2'
        container_name: 'traefik'
        command:
            - '--log.level=DEBUG'
            - '--api.insecure=true'
            - '--providers.docker=true'
            - '--providers.docker.exposedbydefault=false'
            - '--entrypoints.web.address=:80'
            - '--providers.docker.network=traefik-network'
        ports:
            - '3000:80'
            - '8080:8080'
        networks:
            - traefik-network
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
