version: '3.8'
services:
    sut:
        container_name: prytaneum-front-end
        environment: 
            - CI=true
        build:
            context: .
            dockerfile: Dockerfile
            target: base-stage
        command: 'yarn test'
        volumes:
            - ./src:/usr/app/src
            - ./public:/usr/app/public
            - ./.env:/usr/app/.env
            - ./tsconfig.json:/usr/app/tsconfig.json
        ports:
            - '3000:3000'
        tty: true
        # stdin_open: true
